<?php

namespace Database\Seeders;

use App\Models\Account;
use App\Models\Site;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

/**
 * Seeds the tenancy primitives: one platform super-admin (global) and two demo
 * accounts, each with an owner user + a site. Site credentials (site_key /
 * widget_secret) are generated by the model's creating hook.
 */
class TenantDemoSeeder extends Seeder
{
    // === CONSTANTS ===
    private const SUPER_ADMIN_EMAIL = 'admin@trayon.test';
    private const DEMO_ACCOUNTS = [
        ['name' => 'Demo Account A', 'owner' => 'owner-a@trayon.test', 'site' => 'Store A'],
        ['name' => 'Demo Account B', 'owner' => 'owner-b@trayon.test', 'site' => 'Store B'],
    ];
    private const DEMO_PASSWORD = 'password';

    public function run(): void
    {
        User::factory()->superAdmin()->create([
            'name' => 'Platform Admin',
            'email' => self::SUPER_ADMIN_EMAIL,
            'password' => Hash::make(self::DEMO_PASSWORD),
        ]);

        foreach (self::DEMO_ACCOUNTS as $spec) {
            $account = Account::factory()->create(['name' => $spec['name']]);

            User::factory()->forAccount($account)->create([
                'name' => $spec['name'].' Owner',
                'email' => $spec['owner'],
                'password' => Hash::make(self::DEMO_PASSWORD),
            ]);

            Site::factory()->forAccount($account)->create(['name' => $spec['site']]);
        }
    }
}
