<?php

namespace Database\Factories;

use App\Models\Account;
use App\Models\Site;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Site>
 *
 * Sets account_id explicitly so the creating hook respects it (no bound tenant
 * required to build a Site in a factory). site_key + widget_secret are
 * generated by the model's creating hook; tests may override them.
 */
class SiteFactory extends Factory
{
    protected $model = Site::class;

    public function definition(): array
    {
        return [
            'account_id' => Account::factory(),
            'name' => fake()->domainWord().' store',
            'domain' => fake()->domainName(),
            'allowed_origins' => ['https://'.fake()->domainName()],
            'free_generations_before_signup' => Site::DEFAULT_FREE_GENERATIONS_BEFORE_SIGNUP,
            'retention_days' => Site::DEFAULT_RETENTION_DAYS,
        ];
    }

    /** Build the site for an existing account. */
    public function forAccount(Account $account): static
    {
        return $this->state(fn () => ['account_id' => $account->id]);
    }
}
