<?php

namespace App\Filament\Merchant\Resources\SiteResource\Pages;

use App\Filament\Merchant\Resources\SiteResource;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

/**
 * M2 — Add-site / onboarding step one. The account_id is stamped by the
 * BelongsToAccount creating-hook under the bound merchant tenant (never set from
 * the form), and the site_key / widget_secret are generated by the model's
 * booted() hook — this page never touches credentials. On success it routes back
 * to the list with a localised confirmation toast.
 */
class CreateSite extends CreateRecord
{
    // === CONSTANTS ===
    protected static string $resource = SiteResource::class;

    private const SAVED_TITLE = 'sites.saved';

    /** Back to the list after a successful create. */
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    /** Localised success toast (replaces Filament's default English one). */
    protected function getCreatedNotification(): ?Notification
    {
        return Notification::make()
            ->success()
            ->title(__(self::SAVED_TITLE));
    }
}
