<?php

use Database\Seeders\StoryboardPipelineSeeder;
use Illuminate\Database\Migrations\Migration;

/**
 * Character fidelity for the storyboard: (1) a new VISION reference-analysis operation describes
 * each uploaded @tag image and the planning prompts treat that description as ground truth;
 * (2) a frame that carries reference images is generated by the operation's `reference_model`
 * (an EDIT-capable fal model that SEES the uploads) instead of the text-to-image default.
 * Full re-seed of the storyboard ops (prompt/param upgrades are the point).
 */
return new class extends Migration
{
    public function up(): void
    {
        (new StoryboardPipelineSeeder)->run();
    }

    public function down(): void
    {
        // Config-only overwrite; nothing tenant-owned to reverse (matches prior seed migrations).
    }
};
