<?php

namespace App\Domain\Platform;

use App\Models\Site;
use App\Support\Tenant;

/**
 * PlatformSiteWriter — the AUDITED super-admin cross-account WRITE seam for Site,
 * the write-side mirror of PlatformSiteQuery.
 *
 * Site is BelongsToAccount; the platform panel binds NO tenant for a super-admin, so a
 * bare Site::create()/update() would hit the creating-guard (no bound tenant) or be
 * hidden by the fail-closed scope. Every write is therefore wrapped in
 * Tenant::run($accountId, …): the BelongsToAccount creating-hook then stamps account_id
 * from the bound tenant (the account the super-admin picked), and the global scope
 * narrows the update to that same account. This BINDS the tenant rather than bypassing
 * the scope — there is NO withoutGlobalScopes() here. Guarded by PlatformGuard.
 */
final class PlatformSiteWriter
{
    /**
     * Create a site owned by $accountId (cross-account, super-admin only).
     *
     * account_id is intentionally NOT in $data — it is non-fillable and is stamped by the
     * BelongsToAccount creating-hook from the bound tenant. site_key / widget_secret are
     * generated by the model's booted() hook.
     *
     * @param  array<string,mixed>  $data
     */
    public function create(int $accountId, array $data): Site
    {
        PlatformGuard::assert();

        return Tenant::run($accountId, static fn (): Site => Site::create($data));
    }

    /**
     * Update a site within its OWN account context (super-admin only). Binding the site's
     * own account_id satisfies the creating/global-scope contract without a scope bypass.
     *
     * @param  array<string,mixed>  $data
     */
    public function update(Site $site, array $data): Site
    {
        PlatformGuard::assert();

        return Tenant::run($site->account_id, static function () use ($site, $data): Site {
            $site->update($data);

            return $site;
        });
    }
}
