<?php

namespace App\Domain\Storyboard;

use App\Domain\Ai\AiOperationResolver;
use App\Domain\Ai\Contracts\ImageGenerationProvider;
use App\Domain\Ai\ImagePayload;
use App\Domain\Ai\OperationConfig;
use App\Domain\Credits\CreditMath;
use App\Domain\Media\MediaStorage;
use App\Models\AiModel;
use App\Models\AiOperation;
use App\Models\StoryboardFrame;
use App\Models\StoryboardFrameVersion;
use Throwable;

/**
 * StoryboardFrameGenerator — generates (and re-generates) the image for one storyboard frame.
 *
 * CONSISTENCY BY CHAINING: every frame after the first is generated by an EDIT-capable model
 * with the PREVIOUS frame's selected image attached as the continuity anchor (same faces,
 * wardrobe, palette, style — new staging), plus the referenced @tag assets. A frame with no
 * anchor (the first, or nothing generated yet) uses the operation's `first_frame_model` —
 * the premium look-setting model — falling back to the default when not catalogued. The
 * PROJECT's aspect ratio overrides the operation's, so a 9:16 film renders 9:16 frames.
 *
 * Every generation records a new frame VERSION and marks it selected (history kept); a locked
 * frame is never touched. NOT a money path — no charge. Failures land the frame in a terminal
 * FAILED state.
 */
final class StoryboardFrameGenerator
{
    // === CONSTANTS ===
    private const MAX_REFERENCES = 4;

    // The ceiling on the WHOLE input payload (own image + continuity anchor + references).
    private const MAX_ATTACHMENTS = 5;

    // Operation param naming the premium model for anchor-less (look-setting) generations.
    private const PARAM_FIRST_FRAME_MODEL = 'first_frame_model';

    // Deterministic continuity leads describing the attached images, in attachment order.
    private const PREVIOUS_SHOT_LEAD = 'The first attached image is the PREVIOUS SHOT of this same film. Keep its characters, faces, wardrobe, lighting, color palette and art style EXACTLY; stage the NEW shot described below.';

    private const OWN_IMAGE_LEAD = 'The first attached image is the CURRENT version of this exact shot. Edit it — keep its composition, characters and style — and apply only the requested change.';

    private const ANCHOR_FOLLOWS_NOTE = 'The next attached image is the previous shot of the film — a continuity reference for characters, wardrobe, lighting and style.';

    private const REFS_FOLLOW_NOTE = 'Any remaining attached images are @tag identity references — identity ground truth only, never their background, pose or lighting.';

    // Single-reference providers (Kling) get ONE image and ONE matching lead.
    private const SINGLE_REF_LEAD = 'The attached image is a @tag identity reference — match the person\'s face, age, hair and body from it, never its background, pose, lighting or camera angle.';

    public function __construct(
        private readonly AiOperationResolver $resolver,
        private readonly StoryboardFrameImageCaller $caller,
        private readonly MediaStorage $media,
    ) {}

    /** Generate a fresh image version (initial generate OR a regenerate/edit). */
    public function generate(StoryboardFrame $frame, ?string $editInstruction = null): void
    {
        if ($frame->is_locked) {
            return;
        }

        $frame->update(['status' => StoryboardFrame::STATUS_GENERATING]);

        // The PROJECT's aspect wins: a TikTok (9:16) project renders 9:16 frames, whatever
        // the operation's own default says.
        $config = $this->resolver->for(AiOperation::KEY_STORYBOARD_FRAME_IMAGE)
            ->withAspectRatio((string) $frame->project->aspect_ratio);

        $ownImage = $this->ownImage($frame);
        $anchor = $this->anchorImage($frame);
        $refs = $this->referenceImages($frame);

        // Resolve the model/provider FIRST — the input payload depends on the provider's
        // capabilities (Kling consumes exactly ONE image), and the prompt leads must never
        // describe attachments the provider does not receive.
        [$model, $provider, $priceHint] = $this->modelFor($config, chained: $ownImage !== null || $anchor !== null);

        [$inputs, $leads] = $provider === ImageGenerationProvider::PROVIDER_KLING
            ? $this->singleImagePayload($ownImage, $anchor, $refs)
            : $this->multiImagePayload($ownImage, $anchor, $refs);

        $prompt = $this->buildPrompt($config, $frame, $editInstruction, $leads);

        // The fallback model only makes sense on the SAME provider's client (callWithFallback
        // runs both through one adapter) — and the resolved provider can differ from the
        // primary when the first-frame upgrade kicked in.
        $fallbackModel = $provider === $config->fallbackProvider ? $config->fallbackModel : null;

        try {
            $result = $this->caller->run($config, $provider, $model, $prompt, $inputs, $priceHint, $fallbackModel);
        } catch (Throwable $e) {
            $frame->update([
                'status' => StoryboardFrame::STATUS_FAILED,
                'meta' => array_merge($frame->meta ?? [], ['error' => $e->getMessage()]),
            ]);

            return;
        }

        $stored = $this->media->storeStoryboardFrame($frame->project_id, $frame->id, $result->imageBytes, $result->mimeType);

        $this->recordVersion($frame, $stored->path, $prompt, $editInstruction, $provider, $result->modelUsed);

        $cost = $result->cost->available && $result->cost->costUsd !== null
            ? CreditMath::usdToMicro($result->cost->costUsd)
            : $priceHint;

        $frame->update([
            'image_path' => $stored->path,
            'status' => StoryboardFrame::STATUS_READY,
            'image_cost_micro_usd' => $cost,
        ]);
    }

    /**
     * The multi-image payload (OpenRouter/fal edit models): own image (edit), then the
     * previous shot (continuity), then the @tag identity references — capped as a whole.
     *
     * @param  array<int,ImagePayload>  $refs
     * @return array{0: array<int,ImagePayload>, 1: array<int,string>}
     */
    private function multiImagePayload(?ImagePayload $ownImage, ?ImagePayload $anchor, array $refs): array
    {
        $inputs = [];
        $leads = [];

        if ($ownImage !== null) {
            $inputs[] = $ownImage;
            $leads[] = self::OWN_IMAGE_LEAD;

            if ($anchor !== null) {
                $inputs[] = $anchor;
                $leads[] = self::ANCHOR_FOLLOWS_NOTE;
            }
        } elseif ($anchor !== null) {
            $inputs[] = $anchor;
            $leads[] = self::PREVIOUS_SHOT_LEAD;
        }

        if ($refs !== []) {
            $leads[] = self::REFS_FOLLOW_NOTE;
        }

        // MAX_ATTACHMENTS caps the WHOLE payload (leading images + references), not just the
        // references — the leads always describe the images that actually survive the cap.
        return [array_slice(array_merge($inputs, $refs), 0, self::MAX_ATTACHMENTS), $leads];
    }

    /**
     * The single-image payload (Kling): the client sends exactly ONE reference, so attach the
     * strongest continuity signal available — the frame's own image (regenerate), else the
     * previous shot (identity propagates through the chain), else the first @tag reference —
     * with ONLY that image's lead sentence.
     *
     * @param  array<int,ImagePayload>  $refs
     * @return array{0: array<int,ImagePayload>, 1: array<int,string>}
     */
    private function singleImagePayload(?ImagePayload $ownImage, ?ImagePayload $anchor, array $refs): array
    {
        if ($ownImage !== null) {
            return [[$ownImage], [self::OWN_IMAGE_LEAD]];
        }

        if ($anchor !== null) {
            return [[$anchor], [self::PREVIOUS_SHOT_LEAD]];
        }

        if ($refs !== []) {
            return [[array_values($refs)[0]], [self::SINGLE_REF_LEAD]];
        }

        return [[], []];
    }

    /** Make a previously generated version the frame's shown image. */
    public function selectVersion(StoryboardFrame $frame, StoryboardFrameVersion $version): void
    {
        if ((int) $version->frame_id !== (int) $frame->getKey()) {
            return;
        }

        // Query-builder writes (not $version->update) so a stale in-memory is_selected can't
        // make the re-select a silent no-op.
        $frame->versions()->update(['is_selected' => false]);
        $frame->versions()->whereKey($version->getKey())->update(['is_selected' => true]);
        $frame->update(['image_path' => $version->image_path]);
    }

    private function recordVersion(StoryboardFrame $frame, string $path, string $prompt, ?string $edit, string $provider, string $model): StoryboardFrameVersion
    {
        $next = (int) $frame->versions()->max('version_number') + 1;
        $frame->versions()->where('is_selected', true)->update(['is_selected' => false]);

        return $frame->versions()->create([
            'image_path' => $path,
            'prompt' => $prompt,
            'negative_prompt' => $frame->negative_prompt,
            'reference_assets' => $frame->reference_tags,
            'edit_instruction' => $edit,
            'provider' => $provider,
            'model' => $model,
            'version_number' => $next,
            'is_selected' => true,
        ]);
    }

    /** @param array<int,string> $leads the input-labeling sentences, in attachment order */
    private function buildPrompt(OperationConfig $config, StoryboardFrame $frame, ?string $edit, array $leads): string
    {
        // The operation's admin-editable system prompt LEADS the prompt (image chat calls carry
        // a single user message, so it is prepended). Substituted with no vars — it must stay
        // placeholder-free. The deterministic input-labeling block follows, then the frame's own
        // image_prompt (written by the scene breakdown).
        $system = trim((string) $config->substituteSystem([]));
        $parts = $system !== '' ? [$system] : [];

        if ($leads !== []) {
            $parts[] = implode(' ', $leads);
        }

        $parts[] = (string) $frame->image_prompt;
        $prompt = implode("\n\n", $parts);

        if ($edit !== null && $edit !== '') {
            $prompt .= "\n\nEdit: ".$edit;
        }

        if (filled($frame->negative_prompt)) {
            $prompt .= "\n\nAvoid: ".$frame->negative_prompt;
        }

        return $prompt;
    }

    /**
     * The model + provider + price for THIS generation. A CHAINED generation (an anchor or the
     * frame's own image leads the inputs) uses the operation's default model — now edit-capable
     * by configuration. An anchor-LESS generation (the look-setting first frame) upgrades to the
     * admin-catalogued `first_frame_model` when present + active. All values come from the DB
     * config (operation params + the ai_models catalog), never a literal.
     *
     * @return array{0: string, 1: string, 2: ?int}
     */
    private function modelFor(OperationConfig $config, bool $chained): array
    {
        $default = [$config->model, $config->provider, $config->estimatedCostMicroUsd ?? $config->modelCostHintMicroUsd];
        $firstFrameModel = trim((string) ($config->params[self::PARAM_FIRST_FRAME_MODEL] ?? ''));

        if ($chained || $firstFrameModel === '' || $firstFrameModel === $config->model) {
            return $default;
        }

        $catalogued = AiModel::query()
            ->where('operation_key', AiOperation::KEY_STORYBOARD_FRAME_IMAGE)
            ->where('model_id', $firstFrameModel)
            ->where('is_active', true)
            ->first();

        if ($catalogued === null) {
            return $default;
        }

        return [
            $catalogued->model_id,
            (string) $catalogued->provider,
            $catalogued->cost_hint_micro_usd ?? $config->estimatedCostMicroUsd,
        ];
    }

    /** The frame's own current image (regenerate/edit), or null. */
    private function ownImage(StoryboardFrame $frame): ?ImagePayload
    {
        if ($frame->image_path === null || ! $this->media->exists($frame->image_path)) {
            return null;
        }

        $signed = $this->media->signedUrl($frame->image_path);

        return $signed !== null ? ImagePayload::fromUrl($signed) : null;
    }

    /**
     * The continuity anchor: the nearest EARLIER frame that already has a selected image. Null
     * for the first frame (or when nothing before it has been generated yet).
     */
    private function anchorImage(StoryboardFrame $frame): ?ImagePayload
    {
        // reorder() FIRST: the frames() relation is declared with orderBy('frame_number'),
        // and appending a desc key would only ADD a second sort ("asc, desc") — the asc key
        // would still win and hand us frame 1 for the whole film instead of the previous shot.
        $previous = $frame->project->frames()
            ->where('frame_number', '<', (int) $frame->frame_number)
            ->whereNotNull('image_path')
            ->reorder('frame_number', 'desc')
            ->first();

        if ($previous === null || ! $this->media->exists($previous->image_path)) {
            return null;
        }

        $signed = $this->media->signedUrl($previous->image_path);

        return $signed !== null ? ImagePayload::fromUrl($signed) : null;
    }

    /** @return array<int,ImagePayload> the referenced assets' signed image urls, capped */
    private function referenceImages(StoryboardFrame $frame): array
    {
        // Tags from the structured field AND any @tag typed into the prompt (the @-mention flow),
        // so mentioning a reference in the prompt attaches its image. Unicode-aware (Hebrew tags).
        $inPrompt = [];
        if (preg_match_all('/@([\p{L}\p{N}_]+)/u', (string) $frame->image_prompt, $matches)) {
            $inPrompt = $matches[1];
        }

        $tags = array_values(array_unique(array_merge(
            array_map(static fn ($t): string => ltrim((string) $t, '@'), $frame->reference_tags ?? []),
            $inPrompt,
        )));

        if ($tags === []) {
            return [];
        }

        $assets = $frame->project->assets()
            ->whereIn('tag', $tags)
            ->whereNotNull('file_path')
            ->limit(self::MAX_REFERENCES)
            ->get();

        $inputs = [];
        foreach ($assets as $asset) {
            // Skip a reference whose file is missing on the disk — otherwise the provider gets a
            // 404 download and the whole generation fails; proceeding without it still produces an
            // image (just without that reference).
            if (! $this->media->exists($asset->file_path)) {
                continue;
            }

            $signed = $this->media->signedUrl($asset->file_path);
            if ($signed !== null) {
                $inputs[] = ImagePayload::fromUrl($signed);
            }
        }

        return $inputs;
    }
}
