<?php

namespace App\Filament\Platform\Resources;

use App\Domain\Platform\PlatformProductQuery;
use App\Domain\Platform\PlatformSettings;
use App\Domain\Platform\PlatformSiteQuery;
use App\Domain\Platform\PlatformSiteWriter;
use App\Domain\Scan\ScanProductJob;
use App\Domain\Sites\WidgetAppearance;
use App\Filament\Platform\Resources\SiteResource\Pages\CreateSite;
use App\Filament\Platform\Resources\SiteResource\Pages\EditSite;
use App\Filament\Platform\Resources\SiteResource\Pages\ListSites;
use App\Filament\Platform\Resources\SiteResource\Pages\ManageSiteProducts;
use App\Models\Account;
use App\Models\Product;
use App\Models\Site;
use Filament\Forms\Components\ColorPicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TagsInput;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables\Actions\Action;
use Filament\Tables\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;

/**
 * P3 — Sites (cross-account, full CRUD via audited seams).
 *
 * Site IS BelongsToAccount, so a bare Site::query() in the platform panel (which
 * has NO bound tenant for a super-admin) would fail closed and return EMPTY. The
 * table query therefore goes through the AUDITED super-admin seam
 * PlatformSiteQuery::withAccount() — the ONE sanctioned withoutGlobalScope path,
 * guarded by PlatformGuard (super-admin only). There is NO inline
 * withoutGlobalScopes() here.
 *
 * Writes (create/edit) go through the matching audited PlatformSiteWriter, which binds
 * the chosen account via Tenant::run() so the BelongsToAccount creating-guard + global
 * scope hold — a tenant BINDING, not a scope bypass. The super-admin picks the owning
 * account on create (the account_id is fixed on edit). "Setup" is the derived
 * ready/pending indicator the merchant sites list uses (selectors present = ready).
 */
class SiteResource extends Resource
{
    // === CONSTANTS ===
    protected static ?string $model = Site::class;

    protected static ?string $navigationIcon = 'heroicon-o-globe-alt';

    // Attaches to the locked nav order (Sites group) in PlatformPanelProvider.
    protected static ?string $navigationGroup = 'platform.nav.sites';

    protected static ?int $navigationSort = 1;

    // i18n label keys (platform.sites.*).
    private const LABEL_SINGULAR = 'platform.sites.singular';
    private const NAV_LABEL = 'platform.sites.title';

    // Derived setup-state tokens + their plain-badge tones (not the §5 machine).
    private const STATE_READY = 'ready';
    private const STATE_PENDING = 'pending';

    // The widget loader path the install snippet references (app.url + this).
    private const WIDGET_SCRIPT_PATH = '/widget/v1/widget.js';
    private const EMBED_MODAL_VIEW = 'filament.platform.resources.site.embed-modal';

    // The "is this site configured?" verify-setup checklist (modal) view.
    private const VERIFY_MODAL_VIEW = 'filament.platform.resources.site.verify-setup';

    public static function getModelLabel(): string
    {
        return __(self::LABEL_SINGULAR);
    }

    public static function getNavigationLabel(): string
    {
        return __(self::NAV_LABEL);
    }

    public static function getNavigationGroup(): ?string
    {
        return __(self::$navigationGroup);
    }

    /**
     * Create/edit form. On CREATE the super-admin picks the owning account; on EDIT the
     * account is fixed (disabled). The write itself runs through PlatformSiteWriter (it
     * binds the account via Tenant::run); site_key / widget_secret are generated by the
     * model and are never shown or edited here.
     */
    public static function form(Form $form): Form
    {
        return $form->schema([
            Select::make('account_id')
                ->label(__('platform.sites.field.account'))
                ->options(static fn (): array => Account::query()->orderBy('name')->pluck('name', 'id')->all())
                ->searchable()
                ->required()
                ->disabledOn('edit'),
            TextInput::make('name')
                ->label(__('platform.sites.field.name'))
                ->required()
                ->maxLength(255),
            TextInput::make('domain')
                ->label(__('platform.sites.field.domain'))
                ->placeholder(__('platform.sites.field.domain_placeholder'))
                ->url()
                ->maxLength(255),
            TagsInput::make('allowed_origins')
                ->label(__('platform.sites.field.origins'))
                ->helperText(__('platform.sites.field.origins_help')),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name')
                    ->label(__('platform.sites.col.name'))
                    ->weight('medium')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('account.name')
                    ->label(__('platform.sites.col.account'))
                    ->badge()
                    ->color('gray')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('domain')
                    ->label(__('platform.sites.col.domain'))
                    ->color('gray')
                    ->placeholder(__('platform.sites.col.no_domain'))
                    ->searchable(),
                TextColumn::make('setup_state')
                    ->label(__('platform.sites.col.state'))
                    ->badge()
                    ->state(static fn (Site $site): string => self::setupState($site))
                    ->formatStateUsing(static fn (string $state): string => __('platform.sites.state.'.$state))
                    ->color(static fn (string $state): string => $state === self::STATE_READY ? 'success' : 'gray'),
                TextColumn::make('created_at')
                    ->label(__('platform.sites.col.created'))
                    ->since()
                    ->sortable()
                    ->alignEnd(),
            ])
            ->actions([
                self::scanAction(),
                self::productsAction(),
                self::verifyAction(),
                self::appearanceAction(),
                self::embedAction(),
                EditAction::make()
                    ->label(__('platform.sites.edit')),
            ])
            ->emptyStateHeading(__('platform.sites.empty'))
            ->emptyStateDescription(__('platform.sites.empty_sub'))
            ->emptyStateIcon('heroicon-o-globe-alt')
            ->defaultSort('created_at', 'desc');
    }

    /**
     * The table query is the AUDITED cross-account seam (super-admin guarded),
     * eager-loading the owning account. This is the ONLY sanctioned bypass of the
     * BelongsToAccount global scope — never an inline withoutGlobalScopes() here.
     */
    public static function getEloquentQuery(): Builder
    {
        return PlatformSiteQuery::withAccount();
    }

    public static function getPages(): array
    {
        return [
            'index' => ListSites::route('/'),
            'create' => CreateSite::route('/create'),
            'edit' => EditSite::route('/{record}/edit'),
            'products' => ManageSiteProducts::route('/{record}/products'),
        ];
    }

    /**
     * A site is "ready" once it can actually serve a try-on: a CONFIRMED product exists
     * (confirmed selectors live on Product->detected_selectors, not site->selectors). A
     * legacy site->selectors override still counts. The confirmed-product count rides the
     * audited PlatformProductQuery seam (super-admin only). Else the setup is pending.
     */
    private static function setupState(Site $site): string
    {
        if (! empty($site->selectors)) {
            return self::STATE_READY;
        }

        $hasConfirmedProduct = PlatformProductQuery::countForSiteWithStatus(
            (int) $site->getKey(),
            Product::STATUS_CONFIRMED,
        ) > 0;

        return $hasConfirmedProduct ? self::STATE_READY : self::STATE_PENDING;
    }

    /**
     * "Scan a product" — the setup entry point: paste a product-page URL and dispatch
     * the (queued) ScanProductJob with the site's explicit account_id (the job binds the
     * tenant on the worker). The scanned product lands DRAFT for review/confirm; once a
     * product is confirmed the site flips Setup → Ready and the widget button goes live.
     */
    private static function scanAction(): Action
    {
        return Action::make('scan')
            ->label(__('sites.scan.label'))
            ->icon('heroicon-o-magnifying-glass')
            ->color('primary')
            ->modalHeading(__('sites.scan.heading'))
            ->modalDescription(__('sites.scan.sub'))
            ->modalSubmitActionLabel(__('sites.scan.submit'))
            ->form([
                TextInput::make('url')
                    ->label(__('sites.scan.url'))
                    ->placeholder(__('sites.scan.url_placeholder'))
                    ->url()
                    ->required()
                    ->maxLength(2048),
            ])
            ->action(static function (Site $record, array $data): void {
                ScanProductJob::dispatch((int) $record->account_id, (int) $record->getKey(), $data['url']);

                Notification::make()
                    ->success()
                    ->title(__('sites.scan.queued'))
                    ->body(__('sites.scan.queued_body'))
                    ->send();
            });
    }

    /**
     * "Products" — deep-links to the per-site review/confirm page (ManageSiteProducts).
     * There the super-admin reviews a site's scanned products read-only and confirms a
     * DRAFT one. Reads ride the audited PlatformProductQuery seam; confirm runs through
     * the tenant-bound ConfirmScanAction.
     */
    private static function productsAction(): Action
    {
        return Action::make('products')
            ->label(__('platform.sites.products.label'))
            ->icon('heroicon-o-cube')
            ->color('gray')
            ->url(static fn (Site $record): string => ManageSiteProducts::getUrl(['record' => $record->getKey()]));
    }

    /**
     * "Verify setup" — the "is everything configured?" answer: a read-only checklist
     * (✓/✗ + hint) of why the widget button will or won't appear for this site. The
     * confirmed-product check rides the audited PlatformProductQuery seam (super-admin).
     */
    private static function verifyAction(): Action
    {
        return Action::make('verify')
            ->label(__('platform.sites.verify.label'))
            ->icon('heroicon-o-clipboard-document-check')
            ->color('gray')
            ->modalHeading(__('platform.sites.verify.heading'))
            ->modalDescription(__('platform.sites.verify.sub'))
            ->modalSubmitAction(false)
            ->modalCancelActionLabel(__('platform.sites.verify.close'))
            ->modalContent(static fn (Site $record): View => view(self::VERIFY_MODAL_VIEW, [
                'checks' => self::verifyChecklist($record),
            ]));
    }

    /**
     * The setup checklist rows: a stable {key, ok, info, label, hint} list the verify-setup
     * modal renders. Each verifiable row answers one prerequisite for the widget button to
     * appear; the snippet row is informational (cannot be verified server-side).
     *
     * @return array<int,array{key: string, ok: bool, info: bool, label: string, hint: string}>
     */
    private static function verifyChecklist(Site $site): array
    {
        $openRouterSet = app(PlatformSettings::class)->isConfigured(PlatformSettings::OPENROUTER_API_KEY);
        $originsSet = ! empty($site->allowed_origins);
        $confirmedProducts = PlatformProductQuery::countForSiteWithStatus(
            (int) $site->getKey(),
            Product::STATUS_CONFIRMED,
        );

        return [
            self::check('openrouter', $openRouterSet),
            self::check('origins', $originsSet),
            self::check('product', $confirmedProducts > 0),
            // Auto-detected: widget_last_seen_at is stamped when the widget boots on the
            // store (BootstrapController heartbeat), so this flips to ✓ once it's live.
            self::check('snippet', $site->widget_last_seen_at !== null),
        ];
    }

    /**
     * One checklist row with its localised label + hint.
     *
     * @return array{key: string, ok: bool, info: bool, label: string, hint: string}
     */
    private static function check(string $key, bool $ok, bool $info = false): array
    {
        return [
            'key' => $key,
            'ok' => $ok,
            'info' => $info,
            'label' => __('platform.sites.verify.check.'.$key),
            'hint' => __('platform.sites.verify.hint.'.$key),
        ];
    }

    /**
     * "Widget appearance" — set WHERE the Tray On button shows on the store + its look
     * (placement, label, colours, popup theme/accent) for any site, cross-account. The
     * write goes through the audited PlatformSiteWriter (binds the site's account via
     * Tenant::run); values are validated by WidgetAppearance::sanitize. The storefront
     * widget reads the resolved values from the bootstrap API.
     */
    private static function appearanceAction(): Action
    {
        return Action::make('appearance')
            ->label(__('appearance.nav'))
            ->icon('heroicon-o-paint-brush')
            ->color('gray')
            ->modalHeading(__('appearance.title'))
            ->modalSubmitActionLabel(__('appearance.save'))
            ->fillForm(static fn (Site $record): array => WidgetAppearance::resolve($record->widget_appearance))
            ->form([
                Select::make(WidgetAppearance::KEY_PLACEMENT)
                    ->label(__('appearance.button.placement'))
                    ->options(self::placementOptions())
                    ->required(),
                TextInput::make(WidgetAppearance::KEY_LABEL)
                    ->label(__('appearance.button.label'))
                    ->required()
                    ->maxLength(WidgetAppearance::LABEL_MAX),
                ColorPicker::make(WidgetAppearance::KEY_BUTTON_BG)
                    ->label(__('appearance.button.bg'))
                    ->required(),
                ColorPicker::make(WidgetAppearance::KEY_BUTTON_TEXT)
                    ->label(__('appearance.button.text'))
                    ->required(),
                Select::make(WidgetAppearance::KEY_POPUP_THEME)
                    ->label(__('appearance.popup.theme'))
                    ->options(self::themeOptions())
                    ->required(),
                ColorPicker::make(WidgetAppearance::KEY_POPUP_ACCENT)
                    ->label(__('appearance.popup.accent'))
                    ->required(),
            ])
            ->action(static function (Site $record, array $data): void {
                app(PlatformSiteWriter::class)->update($record, [
                    'widget_appearance' => WidgetAppearance::sanitize($data),
                ]);

                Notification::make()
                    ->success()
                    ->title(__('appearance.saved'))
                    ->send();
            });
    }

    /** Placement value => localised label (shared with the merchant appearance page). */
    private static function placementOptions(): array
    {
        $options = [];

        foreach (WidgetAppearance::PLACEMENTS as $placement) {
            $options[$placement] = __('appearance.placement.'.$placement);
        }

        return $options;
    }

    /** Popup theme value => localised label. */
    private static function themeOptions(): array
    {
        $options = [];

        foreach (WidgetAppearance::THEMES as $theme) {
            $options[$theme] = __('appearance.theme.'.$theme);
        }

        return $options;
    }

    /**
     * "Install code" — shows the per-site install snippet (the <script> for the store
     * header) in a read-only modal, reusing the shared embed-code component. Only the
     * PUBLIC site_key is shown; key rotation stays the merchant's action.
     */
    private static function embedAction(): Action
    {
        return Action::make('embed')
            ->label(__('platform.sites.embed.label'))
            ->icon('heroicon-o-code-bracket')
            ->color('gray')
            ->modalHeading(__('platform.sites.embed.heading'))
            ->modalSubmitAction(false)
            ->modalCancelActionLabel(__('platform.sites.embed.close'))
            ->modalContent(static fn (Site $record): View => view(self::EMBED_MODAL_VIEW, [
                'siteKey' => $record->site_key,
                'scriptSrc' => rtrim((string) config('app.url'), '/').self::WIDGET_SCRIPT_PATH,
            ]));
    }
}
