<?php

namespace App\Filament\Platform\Resources;

use App\Domain\Platform\PlatformSiteQuery;
use App\Domain\Platform\PlatformSiteWriter;
use App\Domain\Sites\WidgetAppearance;
use App\Filament\Platform\Resources\SiteResource\Pages\CreateSite;
use App\Filament\Platform\Resources\SiteResource\Pages\EditSite;
use App\Filament\Platform\Resources\SiteResource\Pages\ListSites;
use App\Models\Account;
use App\Models\Site;
use Filament\Forms\Components\ColorPicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TagsInput;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables\Actions\Action;
use Filament\Tables\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;

/**
 * P3 — Sites (cross-account, full CRUD via audited seams).
 *
 * Site IS BelongsToAccount, so a bare Site::query() in the platform panel (which
 * has NO bound tenant for a super-admin) would fail closed and return EMPTY. The
 * table query therefore goes through the AUDITED super-admin seam
 * PlatformSiteQuery::withAccount() — the ONE sanctioned withoutGlobalScope path,
 * guarded by PlatformGuard (super-admin only). There is NO inline
 * withoutGlobalScopes() here.
 *
 * Writes (create/edit) go through the matching audited PlatformSiteWriter, which binds
 * the chosen account via Tenant::run() so the BelongsToAccount creating-guard + global
 * scope hold — a tenant BINDING, not a scope bypass. The super-admin picks the owning
 * account on create (the account_id is fixed on edit). "Setup" is the derived
 * ready/pending indicator the merchant sites list uses (selectors present = ready).
 */
class SiteResource extends Resource
{
    // === CONSTANTS ===
    protected static ?string $model = Site::class;

    protected static ?string $navigationIcon = 'heroicon-o-globe-alt';

    // Attaches to the locked nav order (Sites group) in PlatformPanelProvider.
    protected static ?string $navigationGroup = 'platform.nav.sites';

    protected static ?int $navigationSort = 1;

    // i18n label keys (platform.sites.*).
    private const LABEL_SINGULAR = 'platform.sites.singular';
    private const NAV_LABEL = 'platform.sites.title';

    // Derived setup-state tokens + their plain-badge tones (not the §5 machine).
    private const STATE_READY = 'ready';
    private const STATE_PENDING = 'pending';

    // The widget loader path the install snippet references (app.url + this).
    private const WIDGET_SCRIPT_PATH = '/widget/v1/widget.js';
    private const EMBED_MODAL_VIEW = 'filament.platform.resources.site.embed-modal';

    public static function getModelLabel(): string
    {
        return __(self::LABEL_SINGULAR);
    }

    public static function getNavigationLabel(): string
    {
        return __(self::NAV_LABEL);
    }

    public static function getNavigationGroup(): ?string
    {
        return __(self::$navigationGroup);
    }

    /**
     * Create/edit form. On CREATE the super-admin picks the owning account; on EDIT the
     * account is fixed (disabled). The write itself runs through PlatformSiteWriter (it
     * binds the account via Tenant::run); site_key / widget_secret are generated by the
     * model and are never shown or edited here.
     */
    public static function form(Form $form): Form
    {
        return $form->schema([
            Select::make('account_id')
                ->label(__('platform.sites.field.account'))
                ->options(static fn (): array => Account::query()->orderBy('name')->pluck('name', 'id')->all())
                ->searchable()
                ->required()
                ->disabledOn('edit'),
            TextInput::make('name')
                ->label(__('platform.sites.field.name'))
                ->required()
                ->maxLength(255),
            TextInput::make('domain')
                ->label(__('platform.sites.field.domain'))
                ->placeholder(__('platform.sites.field.domain_placeholder'))
                ->url()
                ->maxLength(255),
            TagsInput::make('allowed_origins')
                ->label(__('platform.sites.field.origins'))
                ->helperText(__('platform.sites.field.origins_help')),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name')
                    ->label(__('platform.sites.col.name'))
                    ->weight('medium')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('account.name')
                    ->label(__('platform.sites.col.account'))
                    ->badge()
                    ->color('gray')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('domain')
                    ->label(__('platform.sites.col.domain'))
                    ->color('gray')
                    ->placeholder(__('platform.sites.col.no_domain'))
                    ->searchable(),
                TextColumn::make('setup_state')
                    ->label(__('platform.sites.col.state'))
                    ->badge()
                    ->state(static fn (Site $site): string => self::setupState($site))
                    ->formatStateUsing(static fn (string $state): string => __('platform.sites.state.'.$state))
                    ->color(static fn (string $state): string => $state === self::STATE_READY ? 'success' : 'gray'),
                TextColumn::make('created_at')
                    ->label(__('platform.sites.col.created'))
                    ->since()
                    ->sortable()
                    ->alignEnd(),
            ])
            ->actions([
                self::appearanceAction(),
                self::embedAction(),
                EditAction::make()
                    ->label(__('platform.sites.edit')),
            ])
            ->emptyStateHeading(__('platform.sites.empty'))
            ->emptyStateDescription(__('platform.sites.empty_sub'))
            ->emptyStateIcon('heroicon-o-globe-alt')
            ->defaultSort('created_at', 'desc');
    }

    /**
     * The table query is the AUDITED cross-account seam (super-admin guarded),
     * eager-loading the owning account. This is the ONLY sanctioned bypass of the
     * BelongsToAccount global scope — never an inline withoutGlobalScopes() here.
     */
    public static function getEloquentQuery(): Builder
    {
        return PlatformSiteQuery::withAccount();
    }

    public static function getPages(): array
    {
        return [
            'index' => ListSites::route('/'),
            'create' => CreateSite::route('/create'),
            'edit' => EditSite::route('/{record}/edit'),
        ];
    }

    /** A site is "ready" once its page selectors are wired (scanned), else pending. */
    private static function setupState(Site $site): string
    {
        return ! empty($site->selectors) ? self::STATE_READY : self::STATE_PENDING;
    }

    /**
     * "Widget appearance" — set WHERE the Tray On button shows on the store + its look
     * (placement, label, colours, popup theme/accent) for any site, cross-account. The
     * write goes through the audited PlatformSiteWriter (binds the site's account via
     * Tenant::run); values are validated by WidgetAppearance::sanitize. The storefront
     * widget reads the resolved values from the bootstrap API.
     */
    private static function appearanceAction(): Action
    {
        return Action::make('appearance')
            ->label(__('appearance.nav'))
            ->icon('heroicon-o-paint-brush')
            ->color('gray')
            ->modalHeading(__('appearance.title'))
            ->modalSubmitActionLabel(__('appearance.save'))
            ->fillForm(static fn (Site $record): array => WidgetAppearance::resolve($record->widget_appearance))
            ->form([
                Select::make(WidgetAppearance::KEY_PLACEMENT)
                    ->label(__('appearance.button.placement'))
                    ->options(self::placementOptions())
                    ->required(),
                TextInput::make(WidgetAppearance::KEY_LABEL)
                    ->label(__('appearance.button.label'))
                    ->required()
                    ->maxLength(WidgetAppearance::LABEL_MAX),
                ColorPicker::make(WidgetAppearance::KEY_BUTTON_BG)
                    ->label(__('appearance.button.bg'))
                    ->required(),
                ColorPicker::make(WidgetAppearance::KEY_BUTTON_TEXT)
                    ->label(__('appearance.button.text'))
                    ->required(),
                Select::make(WidgetAppearance::KEY_POPUP_THEME)
                    ->label(__('appearance.popup.theme'))
                    ->options(self::themeOptions())
                    ->required(),
                ColorPicker::make(WidgetAppearance::KEY_POPUP_ACCENT)
                    ->label(__('appearance.popup.accent'))
                    ->required(),
            ])
            ->action(static function (Site $record, array $data): void {
                app(PlatformSiteWriter::class)->update($record, [
                    'widget_appearance' => WidgetAppearance::sanitize($data),
                ]);

                Notification::make()
                    ->success()
                    ->title(__('appearance.saved'))
                    ->send();
            });
    }

    /** Placement value => localised label (shared with the merchant appearance page). */
    private static function placementOptions(): array
    {
        $options = [];

        foreach (WidgetAppearance::PLACEMENTS as $placement) {
            $options[$placement] = __('appearance.placement.'.$placement);
        }

        return $options;
    }

    /** Popup theme value => localised label. */
    private static function themeOptions(): array
    {
        $options = [];

        foreach (WidgetAppearance::THEMES as $theme) {
            $options[$theme] = __('appearance.theme.'.$theme);
        }

        return $options;
    }

    /**
     * "Install code" — shows the per-site install snippet (the <script> for the store
     * header) in a read-only modal, reusing the shared embed-code component. Only the
     * PUBLIC site_key is shown; key rotation stays the merchant's action.
     */
    private static function embedAction(): Action
    {
        return Action::make('embed')
            ->label(__('platform.sites.embed.label'))
            ->icon('heroicon-o-code-bracket')
            ->color('gray')
            ->modalHeading(__('platform.sites.embed.heading'))
            ->modalSubmitAction(false)
            ->modalCancelActionLabel(__('platform.sites.embed.close'))
            ->modalContent(static fn (Site $record): View => view(self::EMBED_MODAL_VIEW, [
                'siteKey' => $record->site_key,
                'scriptSrc' => rtrim((string) config('app.url'), '/').self::WIDGET_SCRIPT_PATH,
            ]));
    }
}
